// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfrdybwafquutnkwwkfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmcmR5YndhZnF1dXRua3d3a2ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NTkwMzUsImV4cCI6MjA2OTAzNTAzNX0.M7j_mKQyv91c6Joz9CxC2pqRyMqproh2Rs2qqRbbi-8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});